In [5]:
import nltk
import numpy as np
import random
import string
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer




In [6]:
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/venukasahi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/venukasahi/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [7]:
filepath='chi.txt'
corpus=open(filepath,'r',errors='ignore')
raw_data=corpus.read()
print(raw_data)

Spirituality is the broad concept of a belief in something beyond the self. It may involve religious traditions centering on the belief in a higher power, but it can also involve a holistic belief in an individual connection to others and to the world as a whole.


Spirituality offers a worldview that suggests there is more to life than just what people experience on a sensory and physical level.
Instead, it suggests that there is something greater that connects all beings to each other and to the universe itself. It also proposes that there is ongoing existence after death and strives to answer questions about the meaning of life, how people are connected to each other, truths about the universe, and other mysteries of human existence.

Spirituality and religious activity have been a source of comfort and relief from stress for multitudes of people. While people use many different religions and paths to find God or to express their spirituality, research has shown that those who are m

In [8]:
print(raw_data.lower())

spirituality is the broad concept of a belief in something beyond the self. it may involve religious traditions centering on the belief in a higher power, but it can also involve a holistic belief in an individual connection to others and to the world as a whole.


spirituality offers a worldview that suggests there is more to life than just what people experience on a sensory and physical level.
instead, it suggests that there is something greater that connects all beings to each other and to the universe itself. it also proposes that there is ongoing existence after death and strives to answer questions about the meaning of life, how people are connected to each other, truths about the universe, and other mysteries of human existence.

spirituality and religious activity have been a source of comfort and relief from stress for multitudes of people. while people use many different religions and paths to find god or to express their spirituality, research has shown that those who are m

In [9]:
sent_tokens=nltk.sent_tokenize(raw_data)
print(sent_tokens)

['Spirituality is the broad concept of a belief in something beyond the self.', 'It may involve religious traditions centering on the belief in a higher power, but it can also involve a holistic belief in an individual connection to others and to the world as a whole.', 'Spirituality offers a worldview that suggests there is more to life than just what people experience on a sensory and physical level.', 'Instead, it suggests that there is something greater that connects all beings to each other and to the universe itself.', 'It also proposes that there is ongoing existence after death and strives to answer questions about the meaning of life, how people are connected to each other, truths about the universe, and other mysteries of human existence.', 'Spirituality and religious activity have been a source of comfort and relief from stress for multitudes of people.', 'While people use many different religions and paths to find God or to express their spirituality, research has shown tha

In [10]:
print("printing lists in new line")
print(*sent_tokens,sep="\n")

printing lists in new line
Spirituality is the broad concept of a belief in something beyond the self.
It may involve religious traditions centering on the belief in a higher power, but it can also involve a holistic belief in an individual connection to others and to the world as a whole.
Spirituality offers a worldview that suggests there is more to life than just what people experience on a sensory and physical level.
Instead, it suggests that there is something greater that connects all beings to each other and to the universe itself.
It also proposes that there is ongoing existence after death and strives to answer questions about the meaning of life, how people are connected to each other, truths about the universe, and other mysteries of human existence.
Spirituality and religious activity have been a source of comfort and relief from stress for multitudes of people.
While people use many different religions and paths to find God or to express their spirituality, research has sh

In [11]:
word_tokens=nltk.word_tokenize(raw_data)

In [12]:
print(len(sent_tokens),len(word_tokens))

291 8074


In [13]:
lemmer=nltk.stem.WordNetLemmatizer()
def LemTokens(tokens):
    return[lemmer.lemmatize(token)for token in tokens]

In [14]:
remove_punct_dict=dict((ord(punct),None)for punct in string.punctuation)
def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))


In [15]:
test_sentence='Spirituality enhances mental and physical well-being!'
test_word_tokens=nltk.word_tokenize(test_sentence)
lemmer=nltk.stem.WordNetLemmatizer()
def LemTokens(tokens):
    return[lemmer.lemmatize(token)for token in tokens]
LemTokens(test_word_tokens)

['Spirituality', 'enhances', 'mental', 'and', 'physical', 'well-being', '!']

In [16]:
Sentence_1='Yoga is good for mental health'
Sentence_2='Meditation is good for physical health'
Question='what is good for mental health'

In [17]:
Vocabulary=['Yoga','is','good','for','mental','health','Meditation','physical','what']

In [18]:
bag_of_words=np.array([[1,1,1,1,1,1,0,0,0],
                     [0,1,1,1,0,1,1,1,0],
                     [0,1,1,1,1,1,0,0,1]])

In [19]:
bag_of_words[:2,:]

array([[1, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 1, 1, 0]])

In [20]:
print(bag_of_words[-1,:].reshape(1,-1))

[[0 1 1 1 1 1 0 0 1]]


In [21]:
print(bag_of_words[-1,:])

[0 1 1 1 1 1 0 0 1]


In [22]:
cosine_similarity(bag_of_words[:2,:],bag_of_words[-1,:].reshape(1,-1))

array([[0.83333333],
       [0.66666667]])

In [23]:
GREETINGS_INPUTS=["hello","hi","sup","what's up","hey","hey,there","Hi"]
GREETINGS_RESPONSES=["hello","Welcome To UrChi","hey","hi there","Victoria here","I am glad! You are talking to me","What would you like to know?"]

In [24]:
def greeting(sentence):
    for word in sentence.split():
        if word.lower()in GREETINGS_INPUTS:
            return random.choice (GREETINGS_RESPONSES)

In [25]:
greeting('sup')

'hi there'

In [26]:
def response(user_response):
    victoria_response=''
    sent_tokens.append(user_response)
    TfidfVec=TfidfVectorizer(tokenizer=LemNormalize,stop_words='english')
    tfidf=TfidfVec.fit_transform(sent_tokens)
    vals=cosine_similarity(tfidf[-1],tfidf)
    idx=vals.argsort()[0][-2]
    flat=vals.flatten()
    flat.sort()
    req_tfidf=flat[-2]
    if (req_tfidf==0):
        victoria_response=victoria_response+"My bad! This question is beyond my knowledge"
        return victoria_response
    else:
        victoria_response = victoria_response+sent_tokens[idx]
        return victoria_response

In [27]:
response('what is spirituality')

/opt/anaconda3/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:383: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '


'\ufeff\ufeff\n\nSigns of Spirituality\nSpirituality is not a single path or belief system.'

In [29]:

flag=True
print("Victoria:Welcome To UrChi! UrChi is a wonderful platform where we address your mental,physical and emotional problems as well as empower your inner energy-Chi to look more forward in life with further zeal. You can address me as Victoria. What would you like to know? Go ahead and talk about any problems you are facing in life at the moment- mental, phyiscal, emotional. In case you want to quit, please type Bye!")
while(flag==True):
    user_response=input()
    user_response=user_response.lower()
    if(user_response!='bye'):
        if(user_response=='thanks'or user_response=='thank you'):
            flag=False
            print("Victoria:You are always welcome. I am only here to help you!")
        else:
                if(greeting(user_response)!=None):
                    print("Victoria:"+greeting(user_response))
                else:
                    print("Victoria: ",end="")
                    print(response(user_response))
                    sent_tokens.remove(user_response)
        if (user_response=='mental problems'or user_response=='mental'):
            flag=False
            print("Victoria:No problem! Those can be fixed anyhow,either through yoga, meditation or psychological treatment. If it relates to social problems, chisel your interpersonal skills by being with those people who empower your Chi and constantly motivate you in life.")
        elif (user_response=='physical problems'or user_response=='physical'):
                print("Victoria:Ah! That's not an issue. We'll fix that in a giffy. Physical problems such as constant excruciating pain in the head is common including gastrointestinal problems however this is all due to the daily stress you face. So, we have to eradicate the root-cause of this. Yoga enhances the power of chakras which are energy points and hence increases our bodily productivity while plummets the lethargy of everyday life. ")
        else:
            if(user_response=='emotional problems'or user_response=='emotional'):
                 print("Victoria:Who doesn't have emotional problems?! When I have some fear or lose of control of my emotions, I take three deep breaths, reminding myself powerful affirmations such as everything will go great, I am strong, I am beautiful. These words emanate positive energy to me and give assurance. I think you should do the same too. If you see any improvement, you can always say thanks to me!:)")
    else:
        flag=False
        print("Victoria: Bye! Have A Great Day Ahead & Keep Empowering Your Chi!For more spiritual learnings, visit our site: thesacredtruthoftheuniverse.blogspot.com")
                
    

Victoria:Welcome To UrChi! UrChi is a wonderful platform where we address your mental,physical and emotional problems as well as empower your inner energy-Chi to look more forward in life with further zeal. You can address me as Victoria. What would you like to know? Go ahead and talk about any problems you are facing in life at the moment- mental, phyiscal, emotional. In case you want to quit, please type Bye!
hi
Victoria:What would you like to know?
who is god?
Victoria: Imam Sadegh (May God’s greetings be upon him) said, “If any one of you gets caught up in one of the worldly sorrows, it isn’t difficult if he/she, after having prayer’s ablution (vozou) goes to the mosque, prays, and asks God to remove his/her sadness.
what are chakras?
Victoria: Yoga maintains that chakras are center points of energy, thoughts, feelings, and the physical body.
what is spirituality?
Victoria: what is spirituality
what is yoga?
Victoria: Ashtanga yoga: This type of yoga uses ancient yoga teachings.
wh